# Generated by Django 3.0.7 on 2020-06-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createproject',
            name='contr_name',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
